CREATE OR REPLACE TABLE transport_dev.integ_transport_assets.map_transport_contract_group AS
SELECT
    raw_contract_name,
    standardised_contract_name,
    CURRENT_TIMESTAMP() AS created_ts,
    CURRENT_TIMESTAMP() AS updated_ts
FROM VALUES
    ('Auckland Traffic Management', 'Auckland Traffic Management'),
    ('Auckland Transport Road Corridor Maintenance & Renewals: West', 'Auckland Transport Road Corridor Maintenance & Renewals: West'),
    ('Auckland West Transport', 'Auckland Transport Road Corridor Maintenance & Renewals: West'),
    ('BP Australian Renewable Energy Hub (AREH) TSP Works', 'BP Australian Renewable Energy Hub (AREH) TSP Works'),
    ('Brisbane Airport', 'R30-BAC Pavement Maintenance Service'),
    ('Brisbane Airport Rail Link (BARL)', 'Brisbane Airport Rail Link (BARL)'),
    ('Citylink Master Works Deed', 'Citylink Master Works Deed'),
    ('Cross City Tunnel O&M', 'Cross City Tunnel O&M'),
    ('Demo Contract', CAST(NULL AS STRING)),
    ('Demo Contract, RAMC - Gen 2 - 2019-2024', CAST(NULL AS STRING)),
    ('Eastern Distributor Tunnel O&M', 'Eastern Distributor Tunnel O&M'),
    ('Eastlink Motorway - Eastlink Alliance', 'Eastlink Motorway - Eastlink Alliance'),
    ('Far North District Council (South) Road Maintenance & Renewals', 'Far North District Council (South) Road Maintenance & Renewals'),
    ('Hauraki District Maintenance Contract', 'Hauraki District Maintenance Contract'),
    ('Initial Capital Projects (ICP), Initial Rehabilitation Works (IRW), Proposed Work Applications (PWA), Western Roads Upgrade (WRU), WRU - DTP Reporting', 'Western Roads Upgrade (WRU)'),
    ('Initial Rehabilitation Works (IRW)', 'Western Roads Upgrade (WRU)'),
    ('Initial Rehabilitation Works (IRW), Proposed Work Applications (PWA)', 'Western Roads Upgrade (WRU)'),
    ('Initial Rehabilitation Works (IRW), Proposed Work Applications (PWA), Western Roads Upgrade (WRU)', 'Western Roads Upgrade (WRU)'),
    ('Initial Rehabilitation Works (IRW), Proposed Work Applications (PWA), Western Roads Upgrade (WRU), WRU - DTP Reporting', 'Western Roads Upgrade (WRU)'),
    ('Initial Rehabilitation Works (IRW), Western Roads Upgrade (WRU)', 'Western Roads Upgrade (WRU)'),
    ('Lane Cove Tunnel/M2 Motorway', 'Lane Cove Tunnel/M2 Motorway'),
    ('Lyttelton Tunnel', 'Lyttelton Tunnel'),
    ('M5 Motorway South West', 'M5 Motorway South West'),
    ('Melton City Council', CAST(NULL AS STRING)),
    ('North East Link (NEL)', 'North East Link (NEL)'),
    ('Port of Brisbane', 'Port of Brisbane Road Corridor Maintenance Services (RCMS) Contract'),
    ('Port of Brisbane Road Corridor Maintenance Services (RCMS) Contract', 'Port of Brisbane Road Corridor Maintenance Services (RCMS) Contract'),
    ('Proposed Work Applications (PWA)', 'Western Roads Upgrade (WRU)'),
    ('Proposed Work Applications (PWA), Western Roads Upgrade (WRU)', 'Western Roads Upgrade (WRU)'),
    ('Quarries NZ', 'Quarries NZ'),
    ('R30-BAC Pavement Maintenance Service', 'R30-BAC Pavement Maintenance Service'),
    ('RAMC - Gen 2 - 2019-2024', 'Road Asset Management Contract (RAMC) Gen 2'),
    ('RAMC - Gen 2 - North', CAST(NULL AS STRING)),
    ('Road Asset Management Contract (RAMC) Gen 2', 'Road Asset Management Contract (RAMC) Gen 2'),
    ('SA Rail', 'SA Rail'),
    ('SRAP-C', 'Sydney Roads Asset Performance Contract (SRAPC) - Parklands'),
    ('SRAP-C OOC', 'Sydney Roads Asset Performance Contract (SRAPC) - Parklands'),
    ('SRAP-C, SRAP-C OOC', 'Sydney Roads Asset Performance Contract (SRAPC) - Parklands'),
    ('Sydney Airport Rail Link (SARL)', 'Sydney Airport Rail Link (SARL)'),
    ('Sydney Harbour Tunnel (SHT)', 'Sydney Harbour Tunnel (SHT) & Western Harbour Tunnel (WHT)'),
    ('Sydney Harbour Tunnel (SHT) & Western Harbour Tunnel (WHT)', 'Sydney Harbour Tunnel (SHT) & Western Harbour Tunnel (WHT)'),
    ('Sydney Roads Asset Performance Contract (SRAPC) - Parklands', 'Sydney Roads Asset Performance Contract (SRAPC) - Parklands'),
    ('Thames Maintenance', 'Thames Maintenance'),
    ('Toowoomba Second Range Crossing', 'TQ Network IR&M'),
    ('Torrens to Darlington (T2D)', 'Torrens to Darlington (T2D)'),
    ('TQ Network IR&M', 'TQ Network IR&M'),
    ('Transmission Gully (O&M)', 'Transmission Gully (O&M)'),
    ('Ventia - Custom Asset Registers', CAST(NULL AS STRING)),
    ('Venture Smart (Statewide Electrical)', 'Venture Smart (Statewide Electrical)'),
    ('VentureSmart', 'Venture Smart (Statewide Electrical)'),
    ('Victorian Road Maintenance Contract (VRMC): Eastern', 'Victorian Road Maintenance Contract (VRMC): Eastern'),
    ('Victorian Road Maintenance Contract (VRMC): Grampians', 'Victorian Road Maintenance Contract (VRMC): Grampians'),
    ('WA Transport', 'WA Transport'),
    ('Western Roads Upgrade (WRU)', 'Western Roads Upgrade (WRU)'),
    ('Whangarei Project Work', 'Whangarei Project Work'),
    ('WRU - DTP Reporting', 'Western Roads Upgrade (WRU)')
AS CONTRACT_MAP(raw_contract_name, standardised_contract_name)
;

