CREATE OR REPLACE VIEW transport_dev.integ_transport_assets.vw_gold_transport_contract_asset_category_data_availability AS
SELECT
    source_context,
    source_label,
    raw_contract_name,
    standardised_contract_name,
    asset_category,
    COUNT(*) AS asset_count,
    ROUND(100.0 * SUM(has_classified_asset_category) / COUNT(*), 1) AS pct_classified_asset_category,
    ROUND(100.0 * SUM(has_raw_asset_type) / COUNT(*), 1) AS pct_raw_asset_type_available,
    ROUND(100.0 * SUM(has_classification) / COUNT(*), 1) AS pct_source_classification_available,
    ROUND(100.0 * SUM(has_spatial_type) / COUNT(*), 1) AS pct_spatial_type_available,
    ROUND(100.0 * SUM(has_wkt) / COUNT(*), 1) AS pct_wkt_available,
    ROUND(100.0 * SUM(has_valid_au_nz_coord) / COUNT(*), 1) AS pct_valid_au_nz_coordinate,
    ROUND(100.0 * SUM(has_chainage) / COUNT(*), 1) AS pct_chainage_available,
    ROUND(100.0 * SUM(has_attribute) / COUNT(*), 1) AS pct_custom_attribute_available,
    ROUND(100.0 * SUM(has_asset_condition) / COUNT(*), 1) AS pct_condition_available,
    ROUND(100.0 * SUM(has_condition_date) / COUNT(*), 1) AS pct_condition_date_available,
    ROUND(100.0 * SUM(has_asset_criticality) / COUNT(*), 1) AS pct_criticality_available,
    ROUND(100.0 * SUM(has_asset_risk) / COUNT(*), 1) AS pct_risk_available,
    ROUND(100.0 * SUM(has_construction_date) / COUNT(*), 1) AS pct_construction_date_available,
    ROUND(100.0 * SUM(has_construction_cost) / COUNT(*), 1) AS pct_construction_cost_available,
    ROUND(100.0 * SUM(has_useful_life) / COUNT(*), 1) AS pct_useful_life_available,
    ROUND(100.0 * SUM(has_job) / COUNT(*), 1) AS pct_job_linked,
    ROUND(100.0 * SUM(has_completed_job) / COUNT(*), 1) AS pct_completed_job_available,
    ROUND(100.0 * SUM(has_overdue_job) / COUNT(*), 1) AS pct_overdue_job_available,
    ROUND(100.0 * SUM(has_hazard_defect_code) / COUNT(*), 1) AS pct_hazard_defect_code_available,
    ROUND(100.0 * SUM(has_activity_detail) / COUNT(*), 1) AS pct_activity_detail_available,
    ROUND(100.0 * SUM(has_intervention_code) / COUNT(*), 1) AS pct_intervention_code_available,
    ROUND(100.0 * SUM(has_priority) / COUNT(*), 1) AS pct_priority_available,
    ROUND(100.0 * SUM(has_compliance) / COUNT(*), 1) AS pct_compliance_available,
    ROUND(100.0 * SUM(has_job_quantity) / COUNT(*), 1) AS pct_job_quantity_available,
    ROUND(100.0 * SUM(has_job_dimensions) / COUNT(*), 1) AS pct_job_dimensions_available,
    ROUND(100.0 * SUM(has_inspection) / COUNT(*), 1) AS pct_inspection_linked,
    ROUND(100.0 * SUM(has_completed_inspection) / COUNT(*), 1) AS pct_completed_inspection_available,
    ROUND(100.0 * SUM(has_inspection_type) / COUNT(*), 1) AS pct_inspection_type_available,
    ROUND(100.0 * SUM(has_inspection_schedule) / COUNT(*), 1) AS pct_inspection_schedule_available,
    ROUND(100.0 * SUM(has_capitalwork) / COUNT(*), 1) AS pct_capitalwork_linked,
    ROUND(100.0 * SUM(has_capitalwork_name) / COUNT(*), 1) AS pct_capitalwork_name_available,
    ROUND(100.0 * SUM(has_capitalwork_planned_start) / COUNT(*), 1) AS pct_capitalwork_planned_start_available,
    ROUND(100.0 * SUM(has_completed_capitalwork) / COUNT(*), 1) AS pct_completed_capitalwork_available,
    ROUND(100.0 * SUM(has_photo) / COUNT(*), 1) AS pct_photo_linked,
    ROUND(100.0 * SUM(has_planned_resource) / COUNT(*), 1) AS pct_planned_resource_linked,
    ROUND(100.0 * SUM(has_planned_resource_time) / COUNT(*), 1) AS pct_planned_resource_time_available,
    ROUND(100.0 * SUM(has_planned_resource_quantity) / COUNT(*), 1) AS pct_planned_resource_quantity_available,
    ROUND(100.0 * SUM(has_planned_resource_cost) / COUNT(*), 1) AS pct_planned_resource_cost_available,
    ROUND(100.0 * SUM(has_actual_timesheet) / COUNT(*), 1) AS pct_actual_timesheet_linked,
    ROUND(100.0 * SUM(has_actual_timesheet_time) / COUNT(*), 1) AS pct_actual_timesheet_time_available,
    ROUND(100.0 * SUM(has_actual_timesheet_quantity) / COUNT(*), 1) AS pct_actual_timesheet_quantity_available,
    ROUND(100.0 * SUM(has_actual_timesheet_cost) / COUNT(*), 1) AS pct_actual_timesheet_cost_available
FROM transport_dev.integ_transport_assets.vw_silver_transport_asset_data_availability_detail
WHERE standardised_contract_name IS NOT NULL
GROUP BY
    source_context,
    source_label,
    raw_contract_name,
    standardised_contract_name,
    asset_category
;

