-- Source-table-only extract template for the VentureSmart bad-area prototype.
-- This intentionally avoids curated Transport tables.

SELECT
  ID,
  Contract,
  Region,
  AssetID,
  AssetCode,
  AssetName,
  AssetTypeName,
  Section,
  Area,
  Classification,
  HazardDefectCode,
  HazardCode,
  ActivityCategoryName,
  ActivityName,
  ActivityType,
  InterventionName,
  Priority,
  CreatedDate,
  DueDate,
  ScheduledStart,
  ScheduledEnd,
  CompletedDate,
  CompletedStatus,
  Compliant,
  MadeSafe,
  MadeSafeDateUTC,
  CurrentWorkflowItemCode,
  CurrentWorkflowItemName,
  MergedJobID,
  LinkedJobID,
  EstimatedQuantity,
  ActualQuantity,
  RemainingQuantity,
  EstimatedLength,
  EstimatedWidth,
  EstimatedDepth,
  Direction,
  ReferencePointTypeName,
  ReferencePointName,
  EndReferencePointTypeName,
  EndReferencePointName,
  ChainageFrom,
  ChainageTo,
  DistancePast,
  EndDistancePast,
  Unit,
  Reference1,
  Reference2,
  Comments,
  WKT
FROM ext_mssql_asset_vision_vsm_gen7.dbo.vjob
WHERE COALESCE(Deleted, false) = false
  AND Contract = 'VentureSmart'
  AND Region = 'Western Australia'
  AND WKT IS NOT NULL;
